services:
  main:
    build: .
    container_name: main
    volumes:
      - ./app/src:/app/src
      - ./app/data:/app/data
    restart: "on-failure"
    depends_on:
      pgdatabase:
        condition: service_healthy
  # PostgreSQL Database (Data Warehouse)
  pgdatabase:
    image: postgres:16
    container_name: trades_data_warehouse_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: Trades_Database
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - 5454:5432
    volumes:
      - ./app/volumes/data_postgres:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5 
  # pgAdmin for Database Visualization
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: postgres@postgres.com
      PGADMIN_DEFAULT_PASSWORD: postgres
    ports:
      - 8090:80
    depends_on:
      - pgdatabase
    restart: on-failure
    volumes:
      - ./app/volumes/pgadmin_data:/var/lib/pgadmin

  # Adminer (Lightweight Alternative to pgAdmin) - BONUS
  adminer:
    image: adminer:latest
    container_name: adminer
    ports:
      - "8080:8080"
    depends_on:
      - pgdatabase
    environment:
      ADMINER_DEFAULT_SERVER: pgdatabase

  spark-master:
    image: quay.io/jupyter/pyspark-notebook:2024-10-14
    container_name: spark-master
    command: >
      bash -c "
        mkdir -p /tmp/spark-logs &&
        /usr/local/spark/sbin/start-master.sh &&
        tail -f /tmp/spark-logs/* || tail -f /dev/null
      "
    ports:
      - "8080:8080"
      - "7077:7077"
    environment:
      - SPARK_NO_DAEMONIZE=true
      - SPARK_LOG_DIR=/tmp/spark-logs
      - SPARK_MASTER_HOST=spark-master
      - SPARK_MASTER_PORT=7077
      - SPARK_MASTER_WEBUI_PORT=8080

  spark-worker:
    image: quay.io/jupyter/pyspark-notebook:2024-10-14
    container_name: spark-worker
    command: >
      bash -c "
        mkdir -p /tmp/spark-logs /tmp/spark-work &&
        /usr/local/spark/sbin/start-worker.sh spark://spark-master:7077 &&
        tail -f /tmp/spark-logs/* || tail -f /dev/null
      "
    depends_on:
      - spark-master
    ports:
      - "8081:8081"
    environment:
      - SPARK_NO_DAEMONIZE=true
      - SPARK_LOG_DIR=/tmp/spark-logs
      - SPARK_WORKER_DIR=/tmp/spark-work
      - SPARK_WORKER_CORES=2
      - SPARK_WORKER_MEMORY=2g
      - SPARK_WORKER_WEBUI_PORT=8081
      - SPARK_MASTER=spark://spark-master:7077
  zookeeper:
      image: confluentinc/cp-zookeeper:7.4.0
      container_name: zookeeper
      environment:
        ZOOKEEPER_CLIENT_PORT: 2181
        ZOOKEEPER_TICK_TIME: 2000
      ports:
        - "2181:2181"

  kafka:
    image: confluentinc/cp-kafka:7.4.0
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_CREATE_TOPICS: "55_0654_Topic" # topic:partitions:replication-factor
    depends_on:
      - zookeeper